runtime: python27
version: v01
application: abstract-interp
api_version: 1
threadsafe: true

handlers:

- url: /blog.*
  script: blog.app

- url: /static
  static_dir: static
libraries:
- name: jinja2
  version: latest
- name: ssl
  version: latest
