runtime: python27
version: v01
application: abstract-interp
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static

- url: /.*
  script: blog.app

libraries:
- name: jinja2
  version: latest
- name: ssl
  version: latest
